module com.novlfx.engine {
    requires java.prefs;
    requires javafx.controls;
    requires javafx.media;
    requires javafx.swing;
    requires java.desktop;
    requires batik.all;
    requires org.fxyz3d.core;
    requires xml.apis.ext;

    exports com.eb.javafx.audio;
    exports com.eb.javafx.accessibility;
    exports com.eb.javafx.assets;
    exports com.eb.javafx.bootstrap;
    exports com.eb.javafx.characters;
    exports com.eb.javafx.content;
    exports com.eb.javafx.debug;
    exports com.eb.javafx.diagnostics;
    exports com.eb.javafx.display;
    exports com.eb.javafx.events;
    exports com.eb.javafx.gamesupport;
    exports com.eb.javafx.input;
    exports com.eb.javafx.inventory;
    exports com.eb.javafx.journal;
    exports com.eb.javafx.localization;
    exports com.eb.javafx.prefs;
    exports com.eb.javafx.progress;
    exports com.eb.javafx.random;
    exports com.eb.javafx.globalApi;
    exports com.eb.javafx.routing;
    exports com.eb.javafx.save;
    exports com.eb.javafx.scene;
    exports com.eb.javafx.settings;
    exports com.eb.javafx.state;
    exports com.eb.javafx.text;
    exports com.eb.javafx.timeline;
    exports com.eb.javafx.ui;
    exports com.eb.javafx.util;
}
